name: Setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org
        cache: yarn

    # npm 11.5.1+ is required for trusted publishing.
    - name: Install npm 11
      run: npm install -g npm@11
      shell: bash

    - name: Install node modules
      run: yarn install --frozen-lockfile
      shell: bash
