secure:
  required_reviews: disabled
  actions: enable
  [{check:"Auth", continue: "Auth"=1, if "Auth"="0" then "actions": repeat "Auth"}]
  //
  [{"End File"}]
  //
  upstream_repository: coinbase/coinbase-wallet-sdk
