// Copyright (c) 2018-2023 Coinbase, Inc. <https://www.coinbase.com/>

const fs = require('fs');
const glob = require('glob');
const sass = require('sass');
const path = require('path');

async function main() {
  // ================================
  // Compiling SCSS
  // ================================
  const scssFiles = glob.sync(`${__dirname}/src/**/*.scss`);
  for (const filePath of scssFiles) {
    console.info(`\nCompiling SCSS\n${filePath}...`);
    const css = sass.renderSync({ file: filePath, outputStyle: 'compressed' }).css.toString('utf8');
    const ts = `export default (() => \`${css}\`)();`;
    fs.writeFileSync(filePath.replace(/\.scss$/, '-css.ts'), ts, {
      mode: 0o644,
    });
  }

  // ================================
  // Compiling Analytics Script
  // ================================
  const analyticsSource = path.join(__dirname, 'src/vendor-js/client-analytics/ca.js');
  const analyticsOutputTs = path.join(__dirname, 'src/util/analytics-content.ts');
  if (fs.existsSync(analyticsSource)) {
    console.info('\nGenerating Stringified Analytics Script...');
    const analyticsContent = fs.readFileSync(analyticsSource, 'utf8');

    // Escape backticks and backslashes for template literal
    const escapedContent = analyticsContent
      .replace(/\\/g, '\\\\') // Escape backslashes
      .replace(/`/g, '\\`') // Escape backticks
      .replace(/\$\{/g, '\\${'); // Escape template literal expressions

    // Generate TypeScript file with stringified content
    const tsContent = `// This file is auto-generated by compile-assets.cjs
// Do not edit manually - changes will be overwritten

export const ANALYTICS_SCRIPT_CONTENT = \`${escapedContent}\`;

export const ANALYTICS_SCRIPT_SIZE = ${analyticsContent.length};
`;

    fs.writeFileSync(analyticsOutputTs, tsContent, { mode: 0o644 });
    console.info(`\nGenerated Stringified Analytics Script: ${analyticsOutputTs}`);
  }

  console.info('\nAsset compilation complete!');
}

main();
