name: Bug report
description: Create a report to help us improve
title: "Bug: "
labels: ["type: bug"]

body:
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Coinbase Wallet SDK

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: If applicable, include links to screenshots or error logs

  - type: textarea
    id: desktop
    attributes:
      label: Desktop
      description: Please fill in details for bugs reported on desktop
      placeholder: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

  - type: textarea
    id: smartphone
    attributes:
      label: Smartphone
      description: Please fill in details for bugs reported on smartphone devices
      placeholder: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
