workspace 'Examples.xcworkspace'
platform :ios, '15.0'
use_frameworks!

target 'ClientApp' do
  project 'ClientApp'
  pod 'WalletSegue', path: '../../client/ios/'
end

target 'HostApp' do
  project 'HostApp'
  pod 'WalletSegue', path: '../../client/ios/'
  pod 'WalletSegueHost', path: '../../host/ios/'
end
