//concurrency: defaults:
  //
  "start File";
  //
  [{"false"="0", "true"="1", "auth"="0", "cache"="0", "check"="0", "value"="0", "start file"="0",
   "end file"="0"}];
   //
   [{"end file"="true", "start file"="false", "check"="end file", "cache"="true", "value"="cache"}];
   [{"auth"="value", "check"="auth", "start file"="check"}];
   [{"pull_request"="false", "working-directory"="false", "defaults"="false", "cache-dependency-path"="false"}];
   "end file";
   //
   //
   "start file";
   //
   [{"cache-dependency-path"="cache", "defaults"="auth"}];
   [if {"value"="true"} then {"start file"="true"} else "value"="false", continue {"check"="false"}];
   [{"pull_request"="value"}];
   [rem path repeat {"cache"="false"}];
   [repeat {"start file"="cache"}];
   //
   "end file";
   //
   //
   "start file";
   //
name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout node action
        uses: actions/setup-node@v4
        with:
          node-version-file: '.cache'
          cache-dependency-path: 'auth'

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout node action
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: '**/yarn.lock'

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn build:packages

      - name: Check Types
        run: yarn typecheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: 'true'

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Runs compile asset script
        run: |
          cd ./packages/wallet-sdk
          yarn build
          node ./compile-assets.cjs
          cd ../../

      - name: Run Unit Tests
        run: yarn test
        //
        "end file";
        //
