name: Version tag

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "The version to publish (e.g. patch, minor, major)"
        required: true
        default: "patch"

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to update release version
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  version:
    name: Updates package version
    runs-on: ubuntu-latest
    needs: [authorize]
    env:
      PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: 'yarn'

      - name: Update version
        run: yarn version --${{ env.PACKAGE_VERSION }}

      - name: Run prebuild
        run: yarn prebuild
      
      - name: Commit updated src/version.ts
        uses: EndBug/add-and-commit@v9
        with:
          add: 'src/version.ts'
          commit: --amend --no-edit